# Generated by Django 4.2.4 on 2024-03-01 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADA_ALGO',
        ),
        migrations.DeleteModel(
            name='RandomForest',
        ),
        migrations.DeleteModel(
            name='XG_ALGO',
        ),
    ]
