# Generated by Django 4.2.4 on 2023-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Last_Login_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
